### ISSUE TITLE
Stencil Notification Template - "From" email setting leads to errors sending out mails

### ISSUE THREAD

**Issue by mandrasch** [verbb/formie#1999]
### Describe the bug

Hey, we noticed that the template for email notification trys to set the sender of a form to the sender of the email notification.

![image](https://github.com/user-attachments/assets/2345e36e-11b2-4125-9388-40adda8c812b)

![image](https://github.com/user-attachments/assets/fff73f40-c4b4-4f32-b83b-cb2e70b77795)

![image](https://github.com/user-attachments/assets/cb78751a-7b20-45aa-8ea8-6a7463cdfbc9)

At least in our experience that lead to email send errors because email servers refused to sent out mails for another domain. I don't have the specific error at hand currently, just wanted to let you know.

As far as I know, it would be best to leave that empty?

### Steps to reproduce

1. Select notification template
2. Use Admin Notification from Stencils

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.5.13

### Plugin version

2.1.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
I'm pretty sure we made that change some time ago with the default stencil, as the stencil sets this to the [`replyTo`](https://github.com/verbb/formie/blob/2d961324d861f124c3e8c48db812552904d68428/src/migrations/stencils/contact-form.json#L22) property. Maybe this is an older install that hasn't had this setting updated in the default stencil?

**Comment by mandrasch** [comment]
Hi @engram-design, thx for quick reply!

We have a starter craft project which was migrated from craft v3, could be the case that this wasn't updated properly.

In `config/project/formie/stencils/` we have `contactForm--5...yaml` file:

```
data:
  availability: always
  availabilityFrom: null
  availabilitySubmissions: null
  availabilityTo: null
  dataRetention: forever
  dataRetentionValue: null
  fileUploadsAction: retain
  notifications:
    -
      attachFiles: true
      content: '[{"type":"paragraph","content":[{"type":"text","text":"A user submission has been made on the \""},{"type":"variableTag","attrs":{"label":"Form Name","value":"{formName}"}},{"type":"text","text":"\" form on "},{"type":"variableTag","attrs":{"label":"Site Name","value":"{siteName}"}},{"type":"text","text":" at "},{"type":"variableTag","attrs":{"label":"Timestamp (yyyy-mm-dd hh:mm:ss)","value":"{timestamp}"}}]},{"type":"paragraph","content":[{"type":"text","text":"Their submission details are:"}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enabled: true
      from: '{field.emailAddress}'
      id: new981-8077
      name: 'Admin Notification'
      replyTo: '{field.emailAddress}'
      subject: 'A new submission was made on "{formName}"'
      templateId: ''
      to: '{systemEmail}' 
```

What is the easiest way to update / refresh the Admin Notification template in our starter project?
