### ISSUE TITLE
Updating 1.4.4 to 1.4.5 has broken project config

### ISSUE THREAD

**Issue by nickdunn** [verbb/formie#489]
**Description**
I recently upgraded 1.4.4 to 1.4.5 and now the project-config/apply complains with an error:

>  Your project config files were created for different versions of Craft and/or plugins than what’s currently installed.
>  Formie is installed with schema version of 1.1.9 while 1.1.8 was expected.

Somehow something has got out of sync and I can't figure out a way to resolve it. No combination or series of disabling/reverting the plugin seems to work.

Any ideas how to get out of this cycle?

**Additional info**
- Plugin version: 1.4.5
- Craft version: 3.6.16
- Multi-site: No

**Comment by nickdunn** [comment]
Plugin table shows:

```
formie | 1.4.5 | 1.1.9
```

project.yml shows:

```
  formie:
    edition: standard
    enabled: true
    licenseKey: ...
    schemaVersion: 1.1.9
```
